### Jeudi 21 Decembre - Examen Informatique de L1

##### Les notebook jupyter sont a deposer dans le repertoire "Exam Dec"

Duree de l'examen 2h - vous avez acces a tout document, internet, etc

NB: il y a deux parties independantes, l'une sur les listes et l'autre sur les tableaux

NB: dans le second probleme, lisez bien les commentaires qui accompagnent le code propose

<HR><HR>

### A. manipulations de listes

Voici deux listes pour tester vos fonctions

In [1]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b = [1, 2, 4, 9, 16, 89]

##### A1. ecrire une fonction "smaller_than(num,list)" qui enleve tous les elements < "num" d'une liste "list"

In [2]:
def smaller_than(num,l):
    res = []
    for i in l:
        if i < num:
            res.append(i)
    return res

##### A2. utiliser cette fonction sur les listes a et b ci-dessus, tester sur toutes les valeurs de num de 1  a 10

In [3]:
for i in range(2,10):
    print(smaller_than(i,a))

[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 8]


In [5]:
for i in range(2,10):
    print(smaller_than(i,b))

[1]
[1, 2]
[1, 2]
[1, 2, 4]
[1, 2, 4]
[1, 2, 4]
[1, 2, 4]
[1, 2, 4]


##### A3. definir une fonction "overlap(l1,l2)" qui prend deux listes l1 et l2 en entree et retourne la liste des elements communs a l1 et l2 en sortie - (NB: il n'y a pas de contrainte particuliere sur l'ordre des elements communs)

In [6]:
def overlap(l1,l2):
    res = []
    for i in a:
        for j in b:
            if i == j:
                res.append(i)
    return res

##### A4. appliquer cette fonction overlap a a et b definis plus haut

In [7]:
overlap(a,b)

[1, 2, 4, 9]

In [8]:
overlap(b,a)

[1, 2, 4, 9]

##### A5. definir une variante overlap2 qui ne garde chaque element commun qu'en un seul exemplaire

In [9]:
def overlap2(l1,l2):
    res = []
    for i in a:
        for j in b:
            if (i == j) & (not(i in res)):
                res.append(i)
    return(res)

In [10]:
overlap2(a,b)

[1, 2, 4, 9]

In [11]:
list(set(overlap(a,b)))

[1, 2, 4, 9]

##### A6. definir une fonction min_max(l) qui retourne les elements min et max d'une liste d'entiers l

In [12]:
def min_max(l):
    min = 100
    max = 0
    for i in l:
        if i < min:
            min = i
        if i > min:
            max = i            
    return(min,max)

##### A7. utiliser cette fonction sur les listes a et b ci-dessus

In [13]:
min_max(a)

(1, 10)

In [14]:
min_max(b)

(1, 89)

<HR><HR>

### B. slicing de tableaux

consider the following two dimensional array; you can think of it as a (crude) picture - say 0 is white and 1 is black

In [15]:
A = [[0,0,0,0,0,0],
     [0,0,0,1,0,0],
     [0,1,0,1,0,0],
     [0,0,1,1,0,0],
     [0,0,0,0,0,0],
     [0,0,0,0,0,0]]

##### B1. ecrire une fonction ppa(array) pour "printer" agreablement un tableau et la tester sur Y

In [16]:
def ppa(array):
        for i in range(0,len(array)): 
            print(array[i])

In [17]:
ppa(A)

[0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0]
[0, 1, 0, 1, 0, 0]
[0, 0, 1, 1, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]


##### B2. convertir en un tableau numpy

In [18]:
import numpy as np

In [19]:
B = np.array(A)

In [20]:
ppa(B)

[0 0 0 0 0 0]
[0 0 0 1 0 0]
[0 1 0 1 0 0]
[0 0 1 1 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]


##### B3. calculer B.shape; quelle information obtient-on sur B?

In [21]:
B.shape

(6, 6)

##### B4. What is this slicing operation doing?

In [22]:
D = B[1:5,1:5]
ppa(D)
D.shape # NB: shape returns a pair of dimensions

[0 0 1 0]
[1 0 1 0]
[0 1 1 0]
[0 0 0 0]


(4, 4)

##### B5. extracting sub-images: explain what is happening here

In [23]:
D[0,0] = 9 # setting the 0,0 pixel to 9
ppa(B)

[0 0 0 0 0 0]
[0 9 0 1 0 0]
[0 1 0 1 0 0]
[0 0 1 1 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]


In [24]:
D[0,0] = 0 # setting back the pixel to its initial value
ppa(B)

[0 0 0 0 0 0]
[0 0 0 1 0 0]
[0 1 0 1 0 0]
[0 0 1 1 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]


##### B.6 the following function "nn_0" prints all triples (row index x, column index y, value of the array at x, y)
a) run it to confirm; b) explain what the next function "nn" (which is a slight variant) is counting? It may help to compare B and nn(B) side-by-side!

In [25]:
def nn_0(B):
    for (x, y), element in np.ndenumerate(B):             
        print(x, y, element)

In [26]:
nn_0(D)

0 0 0
0 1 0
0 2 1
0 3 0
1 0 1
1 1 0
1 2 1
1 3 0
2 0 0
2 1 1
2 2 1
2 3 0
3 0 0
3 1 0
3 2 0
3 3 0


In [27]:
def nn(B):
    x_shape, y_shape = B.shape  # retourne les dimensions de B
    NN = np.zeros(B.shape,int)  # initialise un tableau de 0 de memes dimensions que B
    for x in range(1,x_shape-1):
        for y in range(1,y_shape-1):
            NN[x][y] = B[x-1][y-1] + B[x][y-1] + B[x+1][y-1] \
                     + B[x-1][y]               + B[x+1][y]   \
                     + B[x-1][y+1] + B[x][y+1] + B[x+1][y+1]
    return NN # what is NN counting?

In [28]:
ppa(nn(B))

[0 0 0 0 0 0]
[0 1 3 1 2 0]
[0 1 5 3 3 0]
[0 2 3 2 2 0]
[0 1 2 2 1 0]
[0 0 0 0 0 0]


In [29]:
ppa(B)

[0 0 0 0 0 0]
[0 0 0 1 0 0]
[0 1 0 1 0 0]
[0 0 1 1 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]


##### B.7 explain the rules of the game

In [30]:
def transform(B): # this function describes how to update an image
    rows,cols = B.shape
    NN = nn(B)
    for x in range(1,cols-1): # we select pixels that are not on the boundary
        for y in range(1,rows-1): # idem
            if   B[y][x] == 1 and (NN[y][x] < 2 or NN[y][x] > 3):
                 B[y][x] = 0
            elif B[y][x] == 0 and NN[y][x] == 3:
                 B[y][x] = 1
    return B

##### B.8 How many steps before reaching a fixed image?

In [31]:
for i in range(1):
    transform(B)
    ppa(B)
    print(" -> ")

[0 0 0 0 0 0]
[0 0 1 0 0 0]
[0 0 0 1 1 0]
[0 0 1 1 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
 -> 


##### B.9 Change the rules of the game and simulate again